# docker-compose.yml
version: '3'

services:
  # PHP Application Server
  app:
    image: php:8.0-apache
    container_name: smartlib-app
    volumes:
      - ./www/smartlib:/var/www/html
    environment:
      - VIRTUAL_HOST=smartlib.yourdomain.com
      - LETSENCRYPT_HOST=smartlib.yourdomain.com
      - LETSENCRYPT_EMAIL=your-email@example.com
    networks:
      - smartlib-network
      
  # Nginx Proxy Manager for easy domain and HTTPS management
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81' # Admin UI
    volumes:
      - ./data/nginx/data:/data
      - ./data/nginx/letsencrypt:/etc/letsencrypt
    networks:
      - smartlib-network

  # Watchtower for auto-updating containers
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600 # Check for updates every hour
    restart: unless-stopped

networks:
  smartlib-network:
    driver: bridge